#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/bootstrap/app.php';

$run = new Foundation\Console\Run;
$executeState = $run->execute($argv);
$executeState === true ? exit(0) : exit(1);
